apiVersion: v1
kind: Pod
metadata:
  name: my-result-app
  labels:
    app: result
spec:
  containers:
    - image: dockersamples/examplevotingapp_result
      name: result
      ports:
        - containerPort: 80
